<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="mugundhan-Vostro-2520" failures="0" tests="8" name="apitest.Testcase" time="29.095" errors="1" timestamp="2022-05-13T05:37:30 IST" skipped="0">
  <testcase classname="apitest.Testcase" name="GetAllUserScore" time="2.085"/>
  <system-out/>
  <testcase classname="apitest.Testcase" name="LoginwithInvalidUser" time="2.761"/>
  <system-out/>
  <testcase classname="apitest.Testcase" name="RegisterUserPass" time="3.068"/>
  <system-out/>
  <testcase classname="apitest.Testcase" name="RegisterUserFailed" time="1.502"/>
  <system-out/>
  <testcase classname="apitest.Testcase" name="LoginwithNewlyCreatedUser" time="4.886"/>
  <system-out/>
  <testcase classname="apitest.Testcase" name="InsertUserScore" time="6.515"/>
  <system-out/>
  <testcase classname="apitest.Testcase" name="UpdateUserScore" time="6.641"/>
  <system-out/>
  <testcase classname="apitest.Testcase" name="DeleteUserScore" time="1.637">
    <error message="Not able to delete user in Leaderboard. Content of failed Response: io.restassured.internal.RestAssuredResponseImpl@191774d6 , Status Code : 401" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Not able to delete user in Leaderboard. Content of failed Response: io.restassured.internal.RestAssuredResponseImpl@191774d6 , Status Code : 401
at api.EndPoints.DeleteUserinLeaderBoard(EndPoints.java:132)
at apitest.Testcase.DeleteUserScore(Testcase.java:171)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- DeleteUserScore -->
  <system-out/>
</testsuite> <!-- apitest.Testcase -->
